### PR TITLE
Update for Dart 2

### PR DESCRIPTION
**Pull request by sestegra**

### CODE REVIEW

**Review by jingbian — APPROVED** [review]
Thanks for the fixes!

**Comment by benoitjadinon** [comment]
@jingbian would you mind publishing it please ? @sestegra thanks

**Comment by alescdb** [comment]
I'm just wondering why this project (and other dart related projects) is under `https://github.com/google/` and not `https://github.com/dart-lang/` ?

(completely off topic, I agree...)

**Comment by kevmoo** [comment]
@alescdb – this is not a Dart-team supported project.

**Comment by jingbian** [comment]
Package updated.

**Pull request merged**
